### ISSUE TITLE
Provide bot_token to callback functions 

### ISSUE THREAD

**Issue by tzugen** [ryanwinchester/slack_elixir#10]
Using the steps outlined in the Readme, I can create a bot_module, that in effect serves as a collection of callback functions to be invoked when a message is received. 

In my module, I need to call another Slack API to retrieve some additional information related to the message.

The function handle_event in socket.ex has all the information about the bot and the token, but it doesn't pass this on when calling `bot.bot_module.handle_event(type, event)`.

Therefore I cannot cleanly refer to the token, and need to manually retrieve it somehow.

It would be great if the bot module callbacks were supplied with the necessary token, especially when running different bots under the same supervisor, because then its gets messy to figure out which is the correct token.

**Comment by ryanwinchester** [comment]
Added `Bot` struct to `handle_event` in [a4e139d](https://github.com/ryanwinchester/slack_elixir/commit/a4e139d19893e1974b60091c643c3dc897ec58ec)  

and published `1.2.0`
